# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autoNotationView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtWidgets import QMainWindow, QApplication
import sys
import autoNotationCore


class Ui_MainWindow(object):

    def __init__ (self) :
        self.core = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(613, 593)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.avancementLabel = QtWidgets.QLabel(self.centralwidget)
        self.avancementLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.avancementLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.avancementLabel.setFont(font)
        self.avancementLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avancementLabel.setObjectName("avancementLabel")
        self.verticalLayout.addWidget(self.avancementLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.imageView = QtWidgets.QLabel(self.centralwidget)
        self.imageView.setMinimumSize(QtCore.QSize(400, 400))
        self.imageView.setSizeIncrement(QtCore.QSize(0, 0))
        self.imageView.setText("")
        self.imageView.setPixmap(QtGui.QPixmap("../../Pictures/Saved Pictures/39a_12_crs-10_nwramp.jpg"))
        self.imageView.setScaledContents(True)
        self.imageView.setObjectName("imageView")
        self.horizontalLayout.addWidget(self.imageView)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prevButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevButton.setFont(font)
        self.prevButton.setAutoDefault(False)
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout_2.addWidget(self.prevButton)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.annotationLabel = QtWidgets.QLabel(self.centralwidget)
        self.annotationLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.annotationLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.annotationLabel.setFont(font)
        self.annotationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.annotationLabel.setObjectName("annotationLabel")
        self.verticalLayout_2.addWidget(self.annotationLabel)
        self.annotationInput = QtWidgets.QLineEdit(self.centralwidget)
        self.annotationInput.setFont(font)
        self.annotationInput.setAlignment(QtCore.Qt.AlignCenter)
        self.annotationInput.setObjectName("annotationInput")
        self.verticalLayout_2.addWidget(self.annotationInput)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setFont(font)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_2.addWidget(self.nextButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setFont(font)
        self.menuFichier.setObjectName("menuFichier")
        self.menuNavigate = QtWidgets.QMenu(self.menubar)
        self.menuNavigate.setFont(font)
        self.menuNavigate.setObjectName("menuNavigate")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOuvrir = QtWidgets.QAction(MainWindow)
        self.actionOuvrir.setFont(font)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.actionNavigate = QtWidgets.QAction(MainWindow)
        self.actionNavigate.setFont(font)
        self.actionNavigate.setObjectName("actionNavigate")
        self.menuFichier.addAction(self.actionOuvrir)
        self.menuNavigate.addAction(self.actionNavigate)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuNavigate.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # buttons connect
        self.actionOuvrir.triggered.connect(self.didTapOpen)
        self.actionNavigate.triggered.connect(self.didTapNavigate)
        self.prevButton.clicked.connect(self.didTapOnPrevButton)
        self.nextButton.clicked.connect(self.didTapOnNextButton)
        self.annotationInput.returnPressed.connect(self.didTapEnter)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutoNotation"))
        self.avancementLabel.setText(_translate("MainWindow", ""))
        self.prevButton.setText(_translate("MainWindow", "<\n"
"Previous"))
        self.annotationLabel.setText(_translate("MainWindow", "AutoNotation"))
        self.nextButton.setText(_translate("MainWindow", ">\n"
"Next"))
        self.menuFichier.setTitle(_translate("MainWindow", "File"))
        self.menuNavigate.setTitle(_translate("MainWindow", "Navigate"))
        self.actionOuvrir.setText(_translate("MainWindow", "Ouvrir"))
        self.actionNavigate.setText(_translate("MainWindow", "Go to"))

    def setCore(self, core):
        self.core = core
        self.core.setView(self)

    def showImage(self, imagePath) :
        self.imageView.setPixmap(QtGui.QPixmap(imagePath))

    def didTapOnPrevButton(self) :
        if self.core :
            self.core.tapOnPrevButton()

    def didTapOnNextButton(self) :
        if self.core :
            self.core.tapOnNextButton()

    def didTapEnter(self) :
        if self.core :
            self.core.receiveAnnotation(self.annotationInput.text())

    def resetAnnotationInput(self) :
        self.annotationInput.clear()

    def didTapOpen(self) :
        print("try to open")
        fname = QtWidgets.QFileDialog.getOpenFileName(caption = "Choose a file", filter = "dataset (*.csv)")
        if fname :
            print(fname)
            self.core.tapOpen(fname)

    def didTapNavigate(self) :
        msg = QtWidgets.QDialog()
        msg.resize(260, 120)
        msg.setWindowTitle("Choose which index go to")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineInput = QtWidgets.QLineEdit(msg)
        self.lineInput.setObjectName(u"lineInput")
        self.lineInput.setGeometry(QtCore.QRect(30, 20, 200, 40))
        self.okInput = QtWidgets.QPushButton(msg)
        self.okInput.setObjectName(u"okInput")
        self.okInput.setGeometry(QtCore.QRect(100, 75, 60, 40))
        self.okInput.setText("Ok")
        self.okInput.setFont(font)
        self.lineInput.setAlignment(QtCore.Qt.AlignCenter)
        self.lineInput.setFont(font)
        self.lineInput.setValidator(QtGui.QIntValidator())
        self.lineInput.returnPressed.connect(self.didTapEnterPopUp)
        self.okInput.clicked.connect(self.didTapEnterPopUp)
        x = msg.exec_()

    def didTapEnterPopUp(self) :
        if self.core and (self.lineInput.text() != None or self.lineInput.text() != "")  :
            self.core.goToImage(int(self.lineInput.text()))

    def changeAvancementLabel(self, avancement) :
        self.avancementLabel.setText(avancement)

    def changeAnnotationLabel(self, annot) :
        self.annotationLabel.setText(annot)

    def closeEvent(self, event):
        print("close event detected()")
        if self.core:
            print("try to save view")
            self.core.saveAnnotation()
            event.accept() # let the window close
        else:
            event.ignore()

if __name__ == "__main__" :
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    core  = autoNotationCore.AutoNotationCore()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.setCore(core)
    MainWindow.show()
    sys.exit(app.exec_())
